DROP DATABASE IF EXISTS rentomatic;
CREATE DATABASE rentomatic;
USE rentomatic;

CREATE TABLE country (
  id TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL
);

CREATE TABLE city (
  id SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  country_id TINYINT UNSIGNED,

  FOREIGN KEY (country_id) REFERENCES country(id)
  ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE address (
  id MEDIUMINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  street VARCHAR(50) NOT NULL,
  district VARCHAR(20),
  postal_code VARCHAR(10) NOT NULL,
  phone VARCHAR(20),
  city_id SMALLINT UNSIGNED,

  FOREIGN KEY (city_id) REFERENCES city(id)
  ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE customer (
  id MEDIUMINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(45) NOT NULL,
  last_name VARCHAR(45) NOT NULL,
  email VARCHAR(50) NOT NULL UNIQUE,
  created_at DATETIME DEFAULT NOW(),
  is_active BOOLEAN DEFAULT TRUE,
  sub_type ENUM('ONLY_FILMS', 'ONLY_SERIES', 'FILMS_AND_SERIES') NOT NULL,
  address_id MEDIUMINT UNSIGNED,

  FOREIGN KEY (address_id) REFERENCES address(id)
  ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE employee (
  id SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(45) NOT NULL,
  last_name VARCHAR(45) NOT NULL,
  email VARCHAR(50) NOT NULL UNIQUE,
  created_at DATETIME DEFAULT NOW(),
  is_admin BOOLEAN DEFAULT FALSE,
  address_id MEDIUMINT UNSIGNED,

  FOREIGN KEY (address_id) REFERENCES address(id)
  ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE category (
  id TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(25) NOT NULL
);

CREATE TABLE language (
  id TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(20) NOT NULL
);

CREATE TABLE actor (
  id MEDIUMINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(45) NOT NULL,
  last_name VARCHAR(45) NOT NULL
);

CREATE TABLE show_group (
  id MEDIUMINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  poster_path VARCHAR(300),
  release_date DATE
);

CREATE TABLE show_season (
  id MEDIUMINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  season_no TINYINT UNSIGNED DEFAULT 1,
  show_group_id MEDIUMINT UNSIGNED,

  FOREIGN KEY (show_group_id) REFERENCES show_group(id)
  ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE `show` (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(128) NOT NULL,
  description TEXT DEFAULT 'No description.',
  release_date DATE NOT NULL,
  rating ENUM('G', 'PG', 'PG-13', 'R', 'NC-17') NOT NULL,
  special_features SET('Trailers', 'Commentaries', 'Deleted Scenes', 'Behind the Scenes') DEFAULT '',
  is_film BOOLEAN DEFAULT TRUE,
  episode_no SMALLINT DEFAULT 1,
  poster_path VARCHAR(300),
  original_language_id TINYINT UNSIGNED,
  show_season_id MEDIUMINT UNSIGNED,

  FOREIGN KEY (original_language_id) REFERENCES language(id)
  ON DELETE SET NULL ON UPDATE CASCADE,
  FOREIGN KEY (show_season_id) REFERENCES show_season(id)
  ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE show_category (
  show_id INT UNSIGNED,
  category_id TINYINT UNSIGNED,

  PRIMARY KEY (show_id, category_id),
  FOREIGN KEY (show_id) REFERENCES `show`(id)
  ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (category_id) REFERENCES category(id)
  ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE show_language (
  show_id INT UNSIGNED,
  language_id TINYINT UNSIGNED,

  PRIMARY KEY (show_id, language_id),
  FOREIGN KEY (show_id) REFERENCES `show`(id)
  ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (language_id) REFERENCES language(id)
  ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE show_actor (
  show_id INT UNSIGNED,
  actor_id MEDIUMINT UNSIGNED,

  PRIMARY KEY (show_id, actor_id),
  FOREIGN KEY (show_id) REFERENCES `show`(id)
  ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (actor_id) REFERENCES actor(id)
  ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE inventory (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  show_id INT UNSIGNED UNIQUE,

  FOREIGN KEY (show_id) REFERENCES `show`(id)
  ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE rental (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  created_at DATETIME DEFAULT NOW(),
  customer_id MEDIUMINT UNSIGNED,
  inventory_id INT UNSIGNED,

  FOREIGN KEY (customer_id) REFERENCES customer(id)
  ON DELETE SET NULL ON UPDATE CASCADE,
  FOREIGN KEY (inventory_id) REFERENCES inventory(id)
  ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE payment (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  amount DECIMAL(5, 2) NOT NULL,
  created_at DATETIME DEFAULT NOW(),
  customer_id MEDIUMINT UNSIGNED,
  rental_id BIGINT UNSIGNED,

  FOREIGN KEY (customer_id) REFERENCES customer(id)
  ON DELETE SET NULL ON UPDATE CASCADE,
  FOREIGN KEY (rental_id) REFERENCES rental(id)
  ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE price (
  id TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  sub_type ENUM('ONLY_FILMS', 'ONLY_SERIES', 'FILMS_AND_SERIES') NOT NULL,
  show_type ENUM('FILM', 'EPISODE') NOT NULL,
  amount DECIMAL(5, 2) NOT NULL,
  created_at DATETIME DEFAULT NOW()
);

CREATE TABLE customer_log (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  type ENUM('INSERT', 'UPDATE', 'DELETE') NOT NULL,
  `table` VARCHAR(50) NOT NULL,
  was_successful BOOLEAN DEFAULT TRUE,
  created_at DATETIME DEFAULT NOW(),
  customer_id MEDIUMINT UNSIGNED,

  FOREIGN KEY (customer_id) REFERENCES customer(id)
  ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE INDEX actor_last_name_index ON actor(last_name);
